### ISSUE TITLE
few errors on npm run build

### ISSUE THREAD

**Issue by chrismccoy** [paulund/vuejs-wordpress-theme#1]
ERROR in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?
    type=script&index=0!./src/components/pages/Homepage.vue
    Module not found: Error: Can't resolve 'axios' in '/home/chris/sites/vue/src/components/pages'
     @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?
    type=script&index=0!./src/components/pages/Homepage.vue 3:0-26
     @ ./src/components/pages/Homepage.vue
     @ ./src/router/index.js
     @ ./src/main.js

      File to import not found or unreadable: ~bulma.
    Parent style sheet: stdin
          in /home/chris/sites/vue/src/sass/global.scss (line 1, column 1)
     @ ./~/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!./~/vue-style-
    loader!./~/css-loader?{"minimize":true,"sourceMap":true}!./~/vue-loader/lib/style-compiler?
    {"id":"data-v-2a1ff92f","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?
    {"sourceMap":true}!./src/sass/global.scss 4:14-314
     @ ./src/App.vue
     @ ./src/main.js

      File to import not found or unreadable: ~bulma.
    Parent style sheet: stdin
          in /home/chris/sites/vue/src/sass/global.scss (line 1, column 1)
        at runLoaders (/home/chris/sites/vue/node_modules/webpack/lib/NormalModule.js:192:19)
        at /home/chris/sites/vue/node_modules/loader-runner/lib/LoaderRunner.js:364:11
        at /home/chris/sites/vue/node_modules/loader-runner/lib/LoaderRunner.js:230:18
        at context.callback (/home/chris/sites/vue/node_modules/loader-
    runner/lib/LoaderRunner.js:111:13)
        at Object.asyncSassJobQueue.push [as callback] (/home/chris/sites/vue/node_modules/sass-
    loader/lib/loader.js:57:13)
    at Object.<anonymous> (/home/chris/sites/vue/node_modules/async/dist/async.js:2243:31)
    at Object.callback (/home/chris/sites/vue/node_modules/async/dist/async.js:906:16)
    at options.error (/home/chris/sites/vue/node_modules/node-sass/lib/index.js:294:32)

**Comment by paulund** [comment]
Need to install bulma and axois
`npm install bulma`
`npm install axios`
